"""Initial Migration

Revision ID: a846e060da07
Revises: 
Create Date: 2019-08-11 10:53:04.857132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a846e060da07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=True)
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=250), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comments', sa.Column('blogs_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('comment', sa.String(length=255), nullable=True))
    op.add_column('comments', sa.Column('date_posted', sa.DateTime(timezone=250), nullable=True))
    op.add_column('comments', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'blogs', ['blogs_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.drop_column('comments', 'name')
    op.drop_column('comments', 'full_time')
    op.add_column('roles', sa.Column('description', sa.String(length=200), nullable=True))
    op.add_column('roles', sa.Column('id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'roles', ['name'])
    op.drop_column('roles', 'full_time')
    op.add_column('users', sa.Column('author', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'name')
    op.drop_column('users', 'full_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_time', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'id')
    op.drop_column('users', 'email')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'author')
    op.add_column('roles', sa.Column('full_time', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_column('roles', 'id')
    op.drop_column('roles', 'description')
    op.add_column('comments', sa.Column('full_time', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_id')
    op.drop_column('comments', 'id')
    op.drop_column('comments', 'date_posted')
    op.drop_column('comments', 'comment')
    op.drop_column('comments', 'blogs_id')
    op.drop_table('blogs')
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.drop_table('subscribers')
    # ### end Alembic commands ###
